# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShowGif.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1260, 640)
        self.pushButton_return = QtWidgets.QPushButton(Form)
        self.pushButton_return.setGeometry(QtCore.QRect(0, 0, 120, 75))
        self.pushButton_return.setMinimumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_return.setFont(font)
        self.pushButton_return.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_return.setObjectName("pushButton_return")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(270, 30, 691, 481))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_return.setText(_translate("Form", "返回"))
        self.label.setText(_translate("Form", "<html><head/><body><p><img src=\":/data/gif/杨氏干涉演示图.gif\"/></p></body></html>"))


from PyQt5 import QtCore
from PyQt5.QtWidgets import QApplication , QMainWindow, QTableWidgetItem, QMessageBox
import os

path = os.path.abspath('.')
class MainApp(QMainWindow , Ui_MainWindow):

    def __init__(self):
        QMainWindow.__init__(self)


        self.setupUi(self)

        self.setpushButton()


    def setpushButton(self):
        self.pushButton_return.clicked.connect(self.pushButton_return_Clicked)

    def pushButton_return_Clicked(self):
        self.close()

    def showgif(self, path):
        from PyQt5.QtGui import QMovie
        from PyQt5.QtCore import QSize
        self.gif = QMovie(path)
        self.gif.setScaledSize(QSize(691, 481))
        self.label.setMovie(self.gif)
        self.gif.start()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showFullScreen()
    sys.exit(app.exec())