# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie

from mplwidget import MPL_WIDGET


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("background-color: rgb(215, 231, 232);\n"
"/*border-image:url(img/background.jpg)\n"
"")
        self.tableWidget_data_1 = QtWidgets.QTableWidget(MainWindow)
        self.tableWidget_data_1.setGeometry(QtCore.QRect(1340, 130, 281, 231))
        self.tableWidget_data_1.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.tableWidget_data_1.setObjectName("tableWidget_data_1")
        self.tableWidget_data_1.setColumnCount(2)
        self.tableWidget_data_1.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_1.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_data_1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_data_1.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_data_1.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_data_1.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_data_1.setItem(4, 0, item)
        self.horizontalLayoutWidget = QtWidgets.QWidget(MainWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(420, 50, 941, 691))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.Interference_Image = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.Interference_Image.setContentsMargins(0, 0, 0, 0)
        self.Interference_Image.setObjectName("Interference_Image")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(MainWindow)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 330, 442, 126))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.SpinBox_lambda = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.SpinBox_lambda.setMinimumSize(QtCore.QSize(200, 75))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.SpinBox_lambda.setFont(font)
        self.SpinBox_lambda.setStyleSheet("/*QSpinBox*/\n"
"QDoubleSpinBox {\n"
"padding-right: 15px; /* make room for the arrows */\n"
"border:1px solid black;\n"
"border-radius:5px;\n"
"background:rgba(0,0,0,50);\n"
"}\n"
"/*\n"
"QDoubleSpinBox::up-button {\n"
"border-image:url(:/image/images/up_arrow.png)\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"border-image:url(:/image/images/down_arrow.png)\n"
"}\n"
"*/\n"
"\n"
"QDoubleSpinBox::up-button:pressed {\n"
"margin-top:3px;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:pressed {\n"
"margin-bottom:3px;\n"
"}\n"
"/*QSpinBox*/\n"
"QDoubleSpinBox {\n"
"padding-right: 15px; /* make room for the arrows */\n"
"border:1px solid black;\n"
"border-radius:5px;\n"
"background:rgba(0,0,0,50);\n"
"}\n"
"/*\n"
"QDoubleSpinBox::up-button {\n"
"border-image:url(:/image/images/up_arrow.png)\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"border-image:url(:/image/images/down_arrow.png)\n"
"}\n"
"*/\n"
"\n"
"QSpinBox::up-button:pressed {\n"
"margin-top:3px;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:pressed {\n"
"margin-bottom:3px;\n"
"}\n"
"")
        self.SpinBox_lambda.setDecimals(1)
        self.SpinBox_lambda.setMinimum(400.0)
        self.SpinBox_lambda.setMaximum(780.0)
        self.SpinBox_lambda.setSingleStep(0.1)
        self.SpinBox_lambda.setProperty("value", 632.8)
        self.SpinBox_lambda.setObjectName("SpinBox_lambda")
        self.gridLayout_2.addWidget(self.SpinBox_lambda, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(MainWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 100, 441, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(0, 40))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit.setEnabled(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(MainWindow)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 660, 451, 340))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setMaximumSize(QtCore.QSize(1250, 35))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.label_picture = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_picture.setMaximumSize(QtCore.QSize(500, 300))
        self.label_picture.setText("")
        self.label_picture.setPixmap(QtGui.QPixmap("img/迈克尔逊原理图.jfif"))

        # self.gif = QMovie("data/gif/迈克尔逊演示图.gif")
        # self.label_picture.setMovie(self.gif)
        # self.gif.start()

        self.label_picture.setScaledContents(True)
        self.label_picture.setObjectName("label_picture")
        self.verticalLayout_4.addWidget(self.label_picture)
        self.label_result = QtWidgets.QLabel(MainWindow)
        self.label_result.setGeometry(QtCore.QRect(1320, 810, 541, 241))
        self.label_result.setObjectName("label_result")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(MainWindow)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(577, 913, 611, 91))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_n1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_n1.setMaximumSize(QtCore.QSize(300, 50))
        self.label_n1.setObjectName("label_n1")
        self.gridLayout_3.addWidget(self.label_n1, 1, 1, 1, 1)
        self.label_vice_n = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_vice_n.setMaximumSize(QtCore.QSize(300, 25))
        self.label_vice_n.setObjectName("label_vice_n")
        self.gridLayout_3.addWidget(self.label_vice_n, 0, 1, 1, 1)
        self.label_l1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_l1.setMaximumSize(QtCore.QSize(300, 50))
        self.label_l1.setObjectName("label_l1")
        self.gridLayout_3.addWidget(self.label_l1, 1, 0, 1, 1)
        self.label_vice_l = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_vice_l.setMaximumSize(QtCore.QSize(300, 25))
        self.label_vice_l.setObjectName("label_vice_l")
        self.gridLayout_3.addWidget(self.label_vice_l, 0, 0, 1, 1)
        self.tableWidget_result = QtWidgets.QTableWidget(MainWindow)
        self.tableWidget_result.setGeometry(QtCore.QRect(1340, 350, 561, 231))
        self.tableWidget_result.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.tableWidget_result.setObjectName("tableWidget_result")
        self.tableWidget_result.setColumnCount(2)
        self.tableWidget_result.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_result.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_result.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_result.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_result.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_result.setItem(4, 0, item)
        self.tableWidget_data_2 = QtWidgets.QTableWidget(MainWindow)
        self.tableWidget_data_2.setGeometry(QtCore.QRect(1610, 130, 291, 231))
        self.tableWidget_data_2.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.tableWidget_data_2.setObjectName("tableWidget_data_2")
        self.tableWidget_data_2.setColumnCount(2)
        self.tableWidget_data_2.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_data_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_data_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_data_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_data_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_data_2.setItem(4, 0, item)
        self.horizontalSlider = QtWidgets.QSlider(MainWindow)
        self.horizontalSlider.setGeometry(QtCore.QRect(641, 730, 491, 22))
        self.horizontalSlider.setStyleSheet("QSlider \n"
"{\n"
"    background-color: rgba(22, 22, 22, 0.7);\n"
"    border-radius: 5px; /*外边框矩形倒角*/\n"
"}\n"
"\n"
"QSlider::add-page:horizontal\n"
"{\n"
"    background-color: #7A7B79;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal\n"
"{\n"
"    background-color: #7A7B79;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"\n"
" \n"
"QSlider::groove:horizontal\n"
"{\n"
"    height: 6px;\n"
"    background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QSlider::handle:horizontal \n"
"{\n"
"    background: white;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: -4px 0px -4px 0px;\n"
"    border-radius:7px; \n"
"\n"
"}")
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(10000)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setProperty("value", 5000)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_7 = QtWidgets.QLabel(MainWindow)
        self.label_7.setGeometry(QtCore.QRect(550, 720, 81, 41))
        self.label_7.setObjectName("label_7")
        self.SpinBox_e = QtWidgets.QDoubleSpinBox(MainWindow)
        self.SpinBox_e.setGeometry(QtCore.QRect(1140, 730, 81, 21))
        self.SpinBox_e.setMinimumSize(QtCore.QSize(25, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.SpinBox_e.setFont(font)
        self.SpinBox_e.setStyleSheet("/*QSpinBox*/\n"
"QDoubleSpinBox {\n"
"padding-right: 15px; /* make room for the arrows */\n"
"border:1px solid black;\n"
"border-radius:5px;\n"
"background:rgba(0,0,0,50);\n"
"}\n"
"/*\n"
"QDoubleSpinBox::up-button {\n"
"border-image:url(:/image/images/up_arrow.png)\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"border-image:url(:/image/images/down_arrow.png)\n"
"}\n"
"*/\n"
"\n"
"QDoubleSpinBox::up-button:pressed {\n"
"margin-top:3px;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:pressed {\n"
"margin-bottom:3px;\n"
"}\n"
"/*QSpinBox*/\n"
"QDoubleSpinBox {\n"
"padding-right: 15px; /* make room for the arrows */\n"
"border:1px solid black;\n"
"border-radius:5px;\n"
"background:rgba(0,0,0,50);\n"
"}\n"
"/*\n"
"QDoubleSpinBox::up-button {\n"
"border-image:url(:/image/images/up_arrow.png)\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"border-image:url(:/image/images/down_arrow.png)\n"
"}\n"
"*/\n"
"\n"
"QSpinBox::up-button:pressed {\n"
"margin-top:3px;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:pressed {\n"
"margin-bottom:3px;\n"
"}\n"
"")
        self.SpinBox_e.setDecimals(1)
        self.SpinBox_e.setMinimum(1.0)
        self.SpinBox_e.setMaximum(1000.0)
        self.SpinBox_e.setSingleStep(0.1)
        self.SpinBox_e.setProperty("value", 500.0)
        self.SpinBox_e.setObjectName("SpinBox_e")
        self.label_n2 = QtWidgets.QLabel(MainWindow)
        self.label_n2.setGeometry(QtCore.QRect(886, 1000, 300, 50))
        self.label_n2.setMaximumSize(QtCore.QSize(300, 50))
        self.label_n2.setObjectName("label_n2")
        self.label_l2 = QtWidgets.QLabel(MainWindow)
        self.label_l2.setGeometry(QtCore.QRect(578, 1000, 300, 50))
        self.label_l2.setMaximumSize(QtCore.QSize(300, 50))
        self.label_l2.setObjectName("label_l2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(MainWindow)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 460, 441, 171))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setStyleSheet("font: 9pt \"Times New Roman\";")
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.pushButton_recover = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pushButton_recover.setMinimumSize(QtCore.QSize(200, 60))
        self.pushButton_recover.setMaximumSize(QtCore.QSize(180, 60))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_recover.setFont(font)
        self.pushButton_recover.setStyleSheet("QPushButton {\n"
"    font: 18pt \"宋体\";\n"
"    \n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_recover.setObjectName("pushButton_recover")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_recover)
        self.pushButton_help = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pushButton_help.setMinimumSize(QtCore.QSize(200, 60))
        self.pushButton_help.setMaximumSize(QtCore.QSize(180, 60))
        self.pushButton_help.setStyleSheet("QPushButton {\n"
"    font: 18pt \"宋体\";\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_help.setObjectName("pushButton_help")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_help)
        self.pushButton_return = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pushButton_return.setMinimumSize(QtCore.QSize(200, 60))
        self.pushButton_return.setMaximumSize(QtCore.QSize(180, 60))
        self.pushButton_return.setStyleSheet("QPushButton {\n"
"    font: 18pt \"宋体\";\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_return.setObjectName("pushButton_return")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButton_return)
        self.pushButton_show = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pushButton_show.setEnabled(True)
        self.pushButton_show.setMinimumSize(QtCore.QSize(200, 60))
        self.pushButton_show.setMaximumSize(QtCore.QSize(180, 60))
        self.pushButton_show.setStyleSheet("QPushButton {\n"
"    font: 18pt \"宋体\";\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_show.setObjectName("pushButton_show")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_show)
        self.label_Ni = QtWidgets.QLabel(MainWindow)
        self.label_Ni.setGeometry(QtCore.QRect(940, 670, 51, 38))
        self.label_Ni.setObjectName("label_Ni")
        self.label_Ni_text = QtWidgets.QLabel(MainWindow)
        self.label_Ni_text.setGeometry(QtCore.QRect(780, 662, 151, 51))
        self.label_Ni_text.setObjectName("label_Ni_text")
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(720, 20, 351, 51))
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(MainWindow)
        self.formLayoutWidget.setGeometry(QtCore.QRect(1340, 100, 160, 31))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.formLayoutWidget_3 = QtWidgets.QWidget(MainWindow)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(1340, 760, 160, 31))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(MainWindow)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(738, 773, 301, 91))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_main_1 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_main_1.setMaximumSize(QtCore.QSize(300, 50))
        self.label_main_1.setObjectName("label_main_1")
        self.gridLayout_5.addWidget(self.label_main_1, 1, 0, 1, 1)
        self.label_main_6 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_main_6.setMaximumSize(QtCore.QSize(300, 25))
        self.label_main_6.setObjectName("label_main_6")
        self.gridLayout_5.addWidget(self.label_main_6, 0, 0, 1, 1)
        self.label_main_2 = QtWidgets.QLabel(MainWindow)
        self.label_main_2.setGeometry(QtCore.QRect(738, 856, 300, 50))
        self.label_main_2.setMaximumSize(QtCore.QSize(300, 50))
        self.label_main_2.setScaledContents(True)
        self.label_main_2.setObjectName("label_main_2")
        self.formLayoutWidget_4 = QtWidgets.QWidget(MainWindow)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(1400, 590, 409, 159))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.pushButton_in = QtWidgets.QPushButton(self.formLayoutWidget_4)
        self.pushButton_in.setMinimumSize(QtCore.QSize(200, 75))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.pushButton_in.setFont(font)
        self.pushButton_in.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_in.setObjectName("pushButton_in")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_in)
        self.pushButton_clear = QtWidgets.QPushButton(self.formLayoutWidget_4)
        self.pushButton_clear.setMinimumSize(QtCore.QSize(200, 75))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_clear)
        self.pushButton_out = QtWidgets.QPushButton(self.formLayoutWidget_4)
        self.pushButton_out.setMinimumSize(QtCore.QSize(200, 75))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.pushButton_out.setFont(font)
        self.pushButton_out.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_out.setObjectName("pushButton_out")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_out)
        self.pushButton_result = QtWidgets.QPushButton(self.formLayoutWidget_4)
        self.pushButton_result.setMinimumSize(QtCore.QSize(200, 75))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.pushButton_result.setFont(font)
        self.pushButton_result.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_result.setObjectName("pushButton_result")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_result)
        self.pushButton_start = QtWidgets.QPushButton(MainWindow)
        self.pushButton_start.setGeometry(QtCore.QRect(10, 1010, 200, 60))
        self.pushButton_start.setMinimumSize(QtCore.QSize(200, 60))
        self.pushButton_start.setMaximumSize(QtCore.QSize(180, 60))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("QPushButton {\n"
"    font: 18pt \"宋体\";\n"
"    \n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_stop = QtWidgets.QPushButton(MainWindow)
        self.pushButton_stop.setGeometry(QtCore.QRect(260, 1010, 200, 60))
        self.pushButton_stop.setMinimumSize(QtCore.QSize(200, 60))
        self.pushButton_stop.setMaximumSize(QtCore.QSize(180, 60))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setStyleSheet("QPushButton {\n"
"    font: 18pt \"宋体\";\n"
"    \n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.tableWidget_data_1.raise_()
        self.horizontalLayoutWidget.raise_()
        self.gridLayoutWidget_2.raise_()
        self.verticalLayoutWidget.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.label_result.raise_()
        self.gridLayoutWidget_3.raise_()
        self.SpinBox_e.raise_()
        self.horizontalSlider.raise_()
        self.label_7.raise_()
        self.label_n2.raise_()
        self.label_l2.raise_()
        self.formLayoutWidget_2.raise_()
        self.label_Ni.raise_()
        self.label_Ni_text.raise_()
        self.label.raise_()
        self.formLayoutWidget.raise_()
        self.tableWidget_data_2.raise_()
        self.tableWidget_result.raise_()
        self.formLayoutWidget_3.raise_()
        self.gridLayoutWidget_4.raise_()
        self.label_main_2.raise_()
        self.formLayoutWidget_4.raise_()
        self.pushButton_start.raise_()
        self.pushButton_stop.raise_()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mplwidget = MPL_WIDGET(self.centralwidget)
        self.mplwidget.raise_()
        self.mplwidget.setObjectName("mplwidget")
        self.Interference_Image.addWidget(self.mplwidget)

        self.label_main_2.setPixmap(QtGui.QPixmap("img/标线.jpg").scaled(300, 300))
        self.label_l2.setPixmap(QtGui.QPixmap("img/标线.jpg").scaled(300, 300))
        self.label_n2.setPixmap(QtGui.QPixmap("img/标线.jpg").scaled(300, 300))

        # self.label_main_1.setStyleSheet(("QLabel {border-image: url();}"))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        item = self.tableWidget_data_1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_data_1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_data_1.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_data_1.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_data_1.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_data_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "横移条纹数Ni"))
        item = self.tableWidget_data_1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "位置ei(mm)"))
        __sortingEnabled = self.tableWidget_data_1.isSortingEnabled()
        self.tableWidget_data_1.setSortingEnabled(False)
        item = self.tableWidget_data_1.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_data_1.item(1, 0)
        item.setText(_translate("MainWindow", "50"))
        item = self.tableWidget_data_1.item(2, 0)
        item.setText(_translate("MainWindow", "100"))
        item = self.tableWidget_data_1.item(3, 0)
        item.setText(_translate("MainWindow", "150"))
        item = self.tableWidget_data_1.item(4, 0)
        item.setText(_translate("MainWindow", "200"))
        self.tableWidget_data_1.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">入射波长λ(nm)</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">实验参数</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">实验目的</span></p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">1.了解迈克尔逊干涉仪结构，原理</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">2.利用迈克尔逊干涉仪观察干涉现象。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">3.利用迈克尔逊干涉仪测He-Ne激光波长。</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">原理图</span></p></body></html>"))
        self.label_result.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">计算结果</span></p></body></html>"))
        # self.label_n1.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/副尺/vice.jpg\"/></p></body></html>"))
        self.label_vice_n.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#000000;\">副尺N(0.0001mm)</span></p></body></html>"))
        # self.label_l1.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/副尺/vice.jpg\"/></p></body></html>"))
        self.label_vice_l.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#000000;\">副尺L(0.01mm)</span></p></body></html>"))
        item = self.tableWidget_result.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_result.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_result.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_result.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_result.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_result.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ΔN=N(i+5)-Ni"))
        item = self.tableWidget_result.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Δe=e(i+5)-ei"))
        __sortingEnabled = self.tableWidget_result.isSortingEnabled()
        self.tableWidget_result.setSortingEnabled(False)
        item = self.tableWidget_result.item(0, 0)
        item.setText(_translate("MainWindow", "250-0"))
        item = self.tableWidget_result.item(1, 0)
        item.setText(_translate("MainWindow", "300-50"))
        item = self.tableWidget_result.item(2, 0)
        item.setText(_translate("MainWindow", "350-100"))
        item = self.tableWidget_result.item(3, 0)
        item.setText(_translate("MainWindow", "400-150"))
        item = self.tableWidget_result.item(4, 0)
        item.setText(_translate("MainWindow", "450-200"))
        self.tableWidget_result.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_data_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_data_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_data_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_data_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget_data_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget_data_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "横移条纹数Ni"))
        item = self.tableWidget_data_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "位置ei(mm)"))
        __sortingEnabled = self.tableWidget_data_2.isSortingEnabled()
        self.tableWidget_data_2.setSortingEnabled(False)
        item = self.tableWidget_data_2.item(0, 0)
        item.setText(_translate("MainWindow", "250"))
        item = self.tableWidget_data_2.item(1, 0)
        item.setText(_translate("MainWindow", "300"))
        item = self.tableWidget_data_2.item(2, 0)
        item.setText(_translate("MainWindow", "350"))
        item = self.tableWidget_data_2.item(3, 0)
        item.setText(_translate("MainWindow", "400"))
        item = self.tableWidget_data_2.item(4, 0)
        item.setText(_translate("MainWindow", "450"))
        self.tableWidget_data_2.setSortingEnabled(__sortingEnabled)
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">M</span><span style=\" font-size:20pt; vertical-align:sub;\">1位置</span></p></body></html>"))
        # self.label_n2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/标线/标线.jpg\"/></p></body></html>"))
        # self.label_l2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/标线/标线.jpg\"/></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">操作区</span></p></body></html>"))
        self.pushButton_recover.setText(_translate("MainWindow", "恢复默认"))
        self.pushButton_help.setText(_translate("MainWindow", "帮助文档"))
        self.pushButton_return.setText(_translate("MainWindow", "返回主界面"))
        self.pushButton_show.setText(_translate("MainWindow", "显示环数"))
        self.label_Ni.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">0</span></p></body></html>"))
        self.label_Ni_text.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">当前环数：</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600;\">迈克尔逊干涉实验</span></p><p><br/></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">数据区</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">结果展示</span></p></body></html>"))
        # self.label_main_1.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/主尺/main.jpg\"/></p></body></html>"))
        self.label_main_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#000000;\">主尺M(mm)</span></p></body></html>"))
        self.label_main_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/标线/标线.jpg\"/></p></body></html>"))
        self.pushButton_in.setText(_translate("MainWindow", "写入数据"))
        self.pushButton_clear.setText(_translate("MainWindow", "清除数据"))
        self.pushButton_out.setText(_translate("MainWindow", "导出数据"))
        self.pushButton_result.setText(_translate("MainWindow", "开始计算"))
        self.pushButton_start.setText(_translate("MainWindow", "原理演示"))
        self.pushButton_stop.setText(_translate("MainWindow", "暂停演示"))

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showFullScreen()
    sys.exit(app.exec())
