# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiAPP.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("background-color: rgb(210, 217, 209);")
        self.tableWidget_data_1 = QtWidgets.QTableWidget(MainWindow)
        self.tableWidget_data_1.setGeometry(QtCore.QRect(70, 190, 451, 311))
        self.tableWidget_data_1.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.tableWidget_data_1.setObjectName("tableWidget_data_1")
        self.tableWidget_data_1.setColumnCount(3)
        self.tableWidget_data_1.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_1.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_1.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_1.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_1.setHorizontalHeaderItem(2, item)
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(850, 10, 431, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(MainWindow)
        self.formLayoutWidget.setGeometry(QtCore.QRect(70, 110, 514, 74))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.formLayoutWidget_2 = QtWidgets.QWidget(MainWindow)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(610, 110, 461, 44))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.tableWidget_data_2 = QtWidgets.QTableWidget(MainWindow)
        self.tableWidget_data_2.setGeometry(QtCore.QRect(610, 200, 971, 141))
        self.tableWidget_data_2.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.tableWidget_data_2.setObjectName("tableWidget_data_2")
        self.tableWidget_data_2.setColumnCount(7)
        self.tableWidget_data_2.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data_2.setHorizontalHeaderItem(6, item)
        self.textEdit_d0 = QtWidgets.QTextEdit(MainWindow)
        self.textEdit_d0.setGeometry(QtCore.QRect(990, 160, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.textEdit_d0.setFont(font)
        self.textEdit_d0.setObjectName("textEdit_d0")
        self.label_6 = QtWidgets.QLabel(MainWindow)
        self.label_6.setGeometry(QtCore.QRect(740, 165, 251, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(MainWindow)
        self.label_7.setGeometry(QtCore.QRect(1070, 165, 201, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayoutWidget_3 = QtWidgets.QWidget(MainWindow)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(610, 350, 505, 44))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_9 = QtWidgets.QLabel(MainWindow)
        self.label_9.setGeometry(QtCore.QRect(650, 410, 251, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(MainWindow)
        self.label_8.setGeometry(QtCore.QRect(1480, 170, 85, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.textEdit_cylinder = QtWidgets.QTextEdit(MainWindow)
        self.textEdit_cylinder.setGeometry(QtCore.QRect(890, 410, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.textEdit_cylinder.setFont(font)
        self.textEdit_cylinder.setObjectName("textEdit_cylinder")
        self.textEdit_ball = QtWidgets.QTextEdit(MainWindow)
        self.textEdit_ball.setGeometry(QtCore.QRect(1390, 410, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.textEdit_ball.setFont(font)
        self.textEdit_ball.setObjectName("textEdit_ball")
        self.label_10 = QtWidgets.QLabel(MainWindow)
        self.label_10.setGeometry(QtCore.QRect(1210, 410, 181, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(MainWindow)
        self.label_11.setGeometry(QtCore.QRect(1020, 420, 41, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(MainWindow)
        self.label_12.setGeometry(QtCore.QRect(1510, 420, 41, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayoutWidget_4 = QtWidgets.QWidget(MainWindow)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(70, 570, 331, 41))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_1_1 = QtWidgets.QLabel(MainWindow)
        self.label_1_1.setGeometry(QtCore.QRect(70, 620, 331, 181))
        self.label_1_1.setObjectName("label_1_1")
        self.formLayoutWidget_5 = QtWidgets.QWidget(MainWindow)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(440, 570, 331, 41))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_1_2 = QtWidgets.QLabel(MainWindow)
        self.label_1_2.setGeometry(QtCore.QRect(440, 620, 331, 181))
        self.label_1_2.setObjectName("label_1_2")
        self.label_1_3 = QtWidgets.QLabel(MainWindow)
        self.label_1_3.setGeometry(QtCore.QRect(800, 620, 331, 181))
        self.label_1_3.setObjectName("label_1_3")
        self.formLayoutWidget_6 = QtWidgets.QWidget(MainWindow)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(800, 570, 331, 41))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.formLayoutWidget_7 = QtWidgets.QWidget(MainWindow)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(1150, 570, 383, 41))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_1_4 = QtWidgets.QLabel(MainWindow)
        self.label_1_4.setGeometry(QtCore.QRect(1150, 620, 331, 181))
        self.label_1_4.setObjectName("label_1_4")
        self.label_17 = QtWidgets.QLabel(MainWindow)
        self.label_17.setGeometry(QtCore.QRect(70, 520, 441, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(MainWindow)
        self.label_18.setGeometry(QtCore.QRect(70, 810, 371, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.formLayoutWidget_8 = QtWidgets.QWidget(MainWindow)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(80, 850, 331, 41))
        self.formLayoutWidget_8.setObjectName("formLayoutWidget_8")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_1_5 = QtWidgets.QLabel(MainWindow)
        self.label_1_5.setGeometry(QtCore.QRect(80, 900, 331, 181))
        self.label_1_5.setObjectName("label_1_5")
        self.formLayoutWidget_9 = QtWidgets.QWidget(MainWindow)
        self.formLayoutWidget_9.setGeometry(QtCore.QRect(440, 850, 331, 41))
        self.formLayoutWidget_9.setObjectName("formLayoutWidget_9")
        self.formLayout_9 = QtWidgets.QFormLayout(self.formLayoutWidget_9)
        self.formLayout_9.setContentsMargins(0, 0, 0, 0)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_1_6 = QtWidgets.QLabel(MainWindow)
        self.label_1_6.setGeometry(QtCore.QRect(440, 900, 391, 181))
        self.label_1_6.setObjectName("label_1_6")
        self.label_1_7 = QtWidgets.QLabel(MainWindow)
        self.label_1_7.setGeometry(QtCore.QRect(950, 870, 391, 181))
        self.label_1_7.setObjectName("label_1_7")
        self.formLayoutWidget_10 = QtWidgets.QWidget(MainWindow)
        self.formLayoutWidget_10.setGeometry(QtCore.QRect(950, 820, 353, 44))
        self.formLayoutWidget_10.setObjectName("formLayoutWidget_10")
        self.formLayout_10 = QtWidgets.QFormLayout(self.formLayoutWidget_10)
        self.formLayout_10.setContentsMargins(0, 0, 0, 0)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.label_22 = QtWidgets.QLabel(MainWindow)
        self.label_22.setGeometry(QtCore.QRect(1010, 480, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.textEdit_roy_c = QtWidgets.QTextEdit(MainWindow)
        self.textEdit_roy_c.setGeometry(QtCore.QRect(890, 470, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.textEdit_roy_c.setFont(font)
        self.textEdit_roy_c.setObjectName("textEdit_roy_c")
        self.label_23 = QtWidgets.QLabel(MainWindow)
        self.label_23.setGeometry(QtCore.QRect(550, 470, 331, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(MainWindow)
        self.label_24.setGeometry(QtCore.QRect(1120, 470, 271, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.textEdit_ball_2 = QtWidgets.QTextEdit(MainWindow)
        self.textEdit_ball_2.setGeometry(QtCore.QRect(1390, 470, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.textEdit_ball_2.setFont(font)
        self.textEdit_ball_2.setObjectName("textEdit_ball_2")
        self.label_25 = QtWidgets.QLabel(MainWindow)
        self.label_25.setGeometry(QtCore.QRect(1510, 480, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.pushButton_in = QtWidgets.QPushButton(MainWindow)
        self.pushButton_in.setGeometry(QtCore.QRect(1660, 280, 220, 75))
        self.pushButton_in.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_in.setFont(font)
        self.pushButton_in.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_in.setObjectName("pushButton_in")
        self.pushButton_in_2 = QtWidgets.QPushButton(MainWindow)
        self.pushButton_in_2.setGeometry(QtCore.QRect(1660, 390, 220, 75))
        self.pushButton_in_2.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_in_2.setFont(font)
        self.pushButton_in_2.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_in_2.setObjectName("pushButton_in_2")
        self.pushButton_in_3 = QtWidgets.QPushButton(MainWindow)
        self.pushButton_in_3.setGeometry(QtCore.QRect(1660, 500, 220, 75))
        self.pushButton_in_3.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_in_3.setFont(font)
        self.pushButton_in_3.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_in_3.setObjectName("pushButton_in_3")
        self.pushButton_in_4 = QtWidgets.QPushButton(MainWindow)
        self.pushButton_in_4.setGeometry(QtCore.QRect(1660, 610, 220, 75))
        self.pushButton_in_4.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_in_4.setFont(font)
        self.pushButton_in_4.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_in_4.setObjectName("pushButton_in_4")
        self.pushButton_in_5 = QtWidgets.QPushButton(MainWindow)
        self.pushButton_in_5.setGeometry(QtCore.QRect(1660, 730, 220, 75))
        self.pushButton_in_5.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_in_5.setFont(font)
        self.pushButton_in_5.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_in_5.setObjectName("pushButton_in_5")
        self.pushButton_in_6 = QtWidgets.QPushButton(MainWindow)
        self.pushButton_in_6.setGeometry(QtCore.QRect(1660, 170, 220, 75))
        self.pushButton_in_6.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_in_6.setFont(font)
        self.pushButton_in_6.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_in_6.setObjectName("pushButton_in_6")
        self.tableWidget_data_1.raise_()
        self.label.raise_()
        self.formLayoutWidget.raise_()
        self.formLayoutWidget_2.raise_()
        self.tableWidget_data_2.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.formLayoutWidget_3.raise_()
        self.label_9.raise_()
        self.textEdit_d0.raise_()
        self.label_8.raise_()
        self.textEdit_cylinder.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.textEdit_ball.raise_()
        self.formLayoutWidget_4.raise_()
        self.label_1_1.raise_()
        self.formLayoutWidget_5.raise_()
        self.label_1_2.raise_()
        self.label_1_3.raise_()
        self.formLayoutWidget_6.raise_()
        self.formLayoutWidget_7.raise_()
        self.label_1_4.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.formLayoutWidget_8.raise_()
        self.label_1_5.raise_()
        self.formLayoutWidget_9.raise_()
        self.label_1_6.raise_()
        self.label_1_7.raise_()
        self.formLayoutWidget_10.raise_()
        self.label_22.raise_()
        self.textEdit_roy_c.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.textEdit_ball_2.raise_()
        self.label_25.raise_()
        self.pushButton_in.raise_()
        self.pushButton_in_2.raise_()
        self.pushButton_in_3.raise_()
        self.pushButton_in_4.raise_()
        self.pushButton_in_5.raise_()
        self.pushButton_in_6.raise_()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        item = self.tableWidget_data_1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_data_1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_data_1.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_data_1.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_data_1.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_data_1.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_data_1.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "平均值"))
        item = self.tableWidget_data_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "外径D"))
        item = self.tableWidget_data_1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "内径d"))
        item = self.tableWidget_data_1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "高度h"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">测量及误差处理</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">1.空心圆柱体体积的测量</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">单位：mm</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">2.小球直径的测量</span></p></body></html>"))
        item = self.tableWidget_data_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "测量值d\'"))
        item = self.tableWidget_data_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "修正值d"))
        item = self.tableWidget_data_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_data_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_data_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_data_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_data_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_data_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_data_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "d平均值"))
        self.textEdit_d0.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:400;\">螺旋测微器零点读数：d0=</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:400;\">mm，修正值：d=d\'-d0</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">3.测量空心圆柱和小球的质量</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">空心圆柱的质量：</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">单位：mm</span></p></body></html>"))
        self.textEdit_cylinder.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>"))
        self.textEdit_ball.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">小球的质量：</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">KG</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">KG</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">1.1 外径D的计算</span></p></body></html>"))
        self.label_1_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">A类不确定度： mm</span></p><p><span style=\" font-size:16pt;\">B类不确定度： mm</span></p><p><span style=\" font-size:16pt;\">总不确定度： mm</span></p><p><span style=\" font-size:16pt;\">外径测量结果：( ± )mm</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">1.2 内径d的计算</span></p></body></html>"))
        self.label_1_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">A类不确定度： mm</span></p><p><span style=\" font-size:16pt;\">B类不确定度： mm</span></p><p><span style=\" font-size:16pt;\">总不确定度： mm</span></p><p><span style=\" font-size:16pt;\">内径测量结果：( ± )mm</span></p></body></html>"))
        self.label_1_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">A类不确定度： mm</span></p><p><span style=\" font-size:16pt;\">B类不确定度： mm</span></p><p><span style=\" font-size:16pt;\">总不确定度： mm</span></p><p><span style=\" font-size:16pt;\">高度测量结果：( ± )mm</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">1.3 高度h的计算</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">1.4 空心圆柱体体积的计算</span></p></body></html>"))
        self.label_1_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">空心圆柱体体积： mm</span><span style=\" font-size:16pt; vertical-align:super;\">3</span></p><p><span style=\" font-size:16pt;\">体积不确定度： mm</span><span style=\" font-size:16pt; vertical-align:super;\">3</span></p><p><span style=\" font-size:16pt;\">体积测量结果：( ± )mm</span><span style=\" font-size:16pt; vertical-align:super;\">3</span></p><p><span style=\" font-size:16pt;\">空心圆柱密度： kg/m</span><span style=\" font-size:16pt; vertical-align:super;\">3</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">1、空心圆柱体体积的计算</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">2、小钢球体积的计算</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">2.1 直径d的计算</span></p></body></html>"))
        self.label_1_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">A类不确定度： mm</span></p><p><span style=\" font-size:16pt;\">B类不确定度： mm</span></p><p><span style=\" font-size:16pt;\">总不确定度： mm</span></p><p><span style=\" font-size:16pt;\">直径测量结果：( ± )mm</span></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">2.2 小钢球体积的计算</span></p></body></html>"))
        self.label_1_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">小钢球体积： mm</span><span style=\" font-size:16pt; vertical-align:super;\">3</span></p><p><span style=\" font-size:16pt;\">体积不确定度： mm</span><span style=\" font-size:16pt; vertical-align:super;\">3</span></p><p><span style=\" font-size:16pt;\">体积测量结果：( ± )×10</span><span style=\" font-size:16pt; vertical-align:super;\">2</span><span style=\" font-size:16pt;\">mm</span><span style=\" font-size:16pt; vertical-align:super;\">3</span></p><p><span style=\" font-size:16pt;\">小球密度： kg/m</span><span style=\" font-size:16pt; vertical-align:super;\">3</span></p></body></html>"))
        self.label_1_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">空心圆柱密度测量误差： %</span></p><p><span style=\" font-size:16pt;\">小钢球密度测量误差： %</span></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">3、测量误差</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">KG/mm</span><span style=\" font-size:16pt; vertical-align:super;\">3</span></p></body></html>"))
        self.textEdit_roy_c.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">空心圆柱密度的理论值：</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">小球密度的理论值：</span></p></body></html>"))
        self.textEdit_ball_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">KG/mm</span><span style=\" font-size:16pt; vertical-align:super;\">3</span></p></body></html>"))
        self.pushButton_in.setText(_translate("MainWindow", "返回主界面"))
        self.pushButton_in_2.setText(_translate("MainWindow", "计算空心圆柱体"))
        self.pushButton_in_3.setText(_translate("MainWindow", "计算小球"))
        self.pushButton_in_4.setText(_translate("MainWindow", "全部计算"))
        self.pushButton_in_5.setText(_translate("MainWindow", "计算原理"))
        self.pushButton_in_6.setText(_translate("MainWindow", "退出"))

