# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mplwidget import MPL_WIDGET


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1081)
        MainWindow.setStyleSheet("background-color: rgb(215, 231, 232);")
        self.tableWidget = QtWidgets.QTableWidget(MainWindow)
        self.tableWidget.setGeometry(QtCore.QRect(1400, 70, 431, 651))
        self.tableWidget.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(20)
        for i in range(40, 20, -1):
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setVerticalHeaderItem(40 - i, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayoutWidget = QtWidgets.QWidget(MainWindow)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(510, 740, 801, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setStyleSheet("/*QSpinBox*/\n"
"QDoubleSpinBox {\n"
"padding-right: 15px; /* make room for the arrows */\n"
"border:1px solid black;\n"
"border-radius:5px;\n"
"background:rgba(0,0,0,50);\n"
"}\n"
"/*\n"
"QDoubleSpinBox::up-button {\n"
"border-image:url(:/image/images/up_arrow.png)\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"border-image:url(:/image/images/down_arrow.png)\n"
"}\n"
"*/\n"
"\n"
"QDoubleSpinBox::up-button:pressed {\n"
"margin-top:3px;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:pressed {\n"
"margin-bottom:3px;\n"
"}\n"
"/*QSpinBox*/\n"
"QDoubleSpinBox {\n"
"padding-right: 15px; /* make room for the arrows */\n"
"border:1px solid black;\n"
"border-radius:5px;\n"
"background:rgba(0,0,0,50);\n"
"}\n"
"/*\n"
"QDoubleSpinBox::up-button {\n"
"border-image:url(:/image/images/up_arrow.png)\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"border-image:url(:/image/images/down_arrow.png)\n"
"}\n"
"*/\n"
"\n"
"QSpinBox::up-button:pressed {\n"
"margin-top:3px;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:pressed {\n"
"margin-bottom:3px;\n"
"}\n"
"")
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setMinimum(1.0)
        self.doubleSpinBox.setMaximum(100.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setProperty("value", 30.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 0, 0, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.horizontalSlider.setStyleSheet("QSlider \n"
"{\n"
"    background-color: rgba(22, 22, 22, 0.7);\n"
"    border-radius: 5px; /*外边框矩形倒角*/\n"
"}\n"
"\n"
"QSlider::add-page:horizontal\n"
"{\n"
"    background-color: #7A7B79;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal\n"
"{\n"
"    background-color: #7A7B79;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"\n"
" \n"
"QSlider::groove:horizontal\n"
"{\n"
"    height: 6px;\n"
"    background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QSlider::handle:horizontal \n"
"{\n"
"    background: white;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: -4px 0px -4px 0px;\n"
"    border-radius:7px; \n"
"\n"
"}")
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(1000)
        self.horizontalSlider.setProperty("value", 300)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 0, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(MainWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(500, 70, 811, 611))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.Interference_Image = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.Interference_Image.setContentsMargins(0, 0, 0, 0)
        self.Interference_Image.setObjectName("Interference_Image")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(MainWindow)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 270, 481, 361))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_h = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_h.setMinimumSize(QtCore.QSize(0, 75))
        self.comboBox_h.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.comboBox_h.setFont(font)
        self.comboBox_h.setStyleSheet("QComboBox:drop-down{ \n"
"width:30px;  \n"
"height:50px;   \n"
"subcontrol-position: right center;\n"
"subcontrol-origin: padding;\n"
"\n"
"border-left-width :  1px ;\n"
"border-left-color : darkgray;\n"
"border-left-style :  none ; \n"
"\n"
"}\n"
"\n"
"QComboBox{\n"
"padding-right: 15px;\n"
"background:rgba(0,0,0,50);\n"
"border:1px solid black;\n"
"border-radius:5px;\n"
"}\n"
"\n"
"/*下拉样式*/\n"
"/*QComboBox QAbstractItemView {\n"
"color:black; \n"
"background: transparent; \n"
"selection-color:rgba(93,169,255,1);\n"
"selection-background-color: rgba(255,255,255,1);\n"
"}*/")
        self.comboBox_h.setEditable(False)
        self.comboBox_h.setObjectName("comboBox_h")
        self.comboBox_h.addItem("")
        self.comboBox_h.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_h, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.SpinBox_lambda = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.SpinBox_lambda.setMinimumSize(QtCore.QSize(100, 75))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.SpinBox_lambda.setFont(font)
        self.SpinBox_lambda.setStyleSheet("/*QSpinBox*/\n"
"QDoubleSpinBox {\n"
"padding-right: 15px; /* make room for the arrows */\n"
"border:1px solid black;\n"
"border-radius:5px;\n"
"background:rgba(0,0,0,50);\n"
"}\n"
"/*\n"
"QDoubleSpinBox::up-button {\n"
"border-image:url(:/image/images/up_arrow.png)\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"border-image:url(:/image/images/down_arrow.png)\n"
"}\n"
"*/\n"
"\n"
"QDoubleSpinBox::up-button:pressed {\n"
"margin-top:3px;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:pressed {\n"
"margin-bottom:3px;\n"
"}\n"
"/*QSpinBox*/\n"
"QDoubleSpinBox {\n"
"padding-right: 15px; /* make room for the arrows */\n"
"border:1px solid black;\n"
"border-radius:5px;\n"
"background:rgba(0,0,0,50);\n"
"}\n"
"/*\n"
"QDoubleSpinBox::up-button {\n"
"border-image:url(:/image/images/up_arrow.png)\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"border-image:url(:/image/images/down_arrow.png)\n"
"}\n"
"*/\n"
"\n"
"QSpinBox::up-button:pressed {\n"
"margin-top:3px;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:pressed {\n"
"margin-bottom:3px;\n"
"}\n"
"")
        self.SpinBox_lambda.setDecimals(1)
        self.SpinBox_lambda.setMinimum(400.0)
        self.SpinBox_lambda.setMaximum(780.0)
        self.SpinBox_lambda.setSingleStep(0.1)
        self.SpinBox_lambda.setProperty("value", 589.3)
        self.SpinBox_lambda.setObjectName("SpinBox_lambda")
        self.gridLayout_2.addWidget(self.SpinBox_lambda, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 4, 0, 1, 1)
        self.SpinBox_R = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.SpinBox_R.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.SpinBox_R.setFont(font)
        self.SpinBox_R.setStyleSheet("/*QSpinBox*/\n"
"QDoubleSpinBox {\n"
"padding-right: 15px; /* make room for the arrows */\n"
"border:1px solid black;\n"
"border-radius:5px;\n"
"background:rgba(0,0,0,50);\n"
"}\n"
"/*\n"
"QDoubleSpinBox::up-button {\n"
"border-image:url(:/image/images/up_arrow.png)\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"border-image:url(:/image/images/down_arrow.png)\n"
"}\n"
"*/\n"
"\n"
"QDoubleSpinBox::up-button:pressed {\n"
"margin-top:3px;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:pressed {\n"
"margin-bottom:3px;\n"
"}")
        self.SpinBox_R.setDecimals(1)
        self.SpinBox_R.setMinimum(1.0)
        self.SpinBox_R.setMaximum(100.0)
        self.SpinBox_R.setSingleStep(0.1)
        self.SpinBox_R.setProperty("value", 3.0)
        self.SpinBox_R.setObjectName("SpinBox_R")
        self.gridLayout_2.addWidget(self.SpinBox_R, 3, 1, 1, 1)
        self.comboBox_n = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_n.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        self.comboBox_n.setFont(font)
        self.comboBox_n.setStyleSheet("QComboBox:drop-down{ \n"
"width:30px;  \n"
"height:50px;   \n"
"subcontrol-position: right center;\n"
"subcontrol-origin: padding;\n"
"\n"
"border-left-width :  1px ;\n"
"border-left-color : darkgray;\n"
"border-left-style :  none ; \n"
"\n"
"}\n"
"\n"
"QComboBox{\n"
"padding-right: 15px;\n"
"background:rgba(0,0,0,50);\n"
"border:1px solid black;\n"
"border-radius:5px;\n"
"}\n"
"\n"
"/*下拉样式*/\n"
"/*QComboBox QAbstractItemView {\n"
"color:black; \n"
"background: transparent; \n"
"selection-color:rgba(93,169,255,1);\n"
"selection-background-color: rgba(255,255,255,1);\n"
"}*/")
        self.comboBox_n.setEditable(False)
        self.comboBox_n.setObjectName("comboBox_n")
        self.comboBox_n.addItem("")
        self.comboBox_n.addItem("")
        self.comboBox_n.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_n, 4, 1, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(MainWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 70, 481, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(0, 40))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit.setEnabled(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(MainWindow)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 640, 491, 340))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setMaximumSize(QtCore.QSize(1250, 40))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.label_picture = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_picture.setMaximumSize(QtCore.QSize(500, 300))
        self.label_picture.setText("")
        self.label_picture.setPixmap(QtGui.QPixmap("img/原理图.jfif"))
        self.label_picture.setScaledContents(True)
        self.label_picture.setObjectName("label_picture")
        self.verticalLayout_4.addWidget(self.label_picture)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(MainWindow)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(1320, 70, 80, 25))
        self.doubleSpinBox_3.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.doubleSpinBox_3.setFont(font)
        self.doubleSpinBox_3.setStyleSheet("/*QSpinBox*/\n"
"QDoubleSpinBox {\n"
"padding-right: 15px; /* make room for the arrows */\n"
"border:1px solid black;\n"
"border-radius:5px;\n"
"background:rgba(0,0,0,50);\n"
"}\n"
"/*\n"
"QDoubleSpinBox::up-button {\n"
"border-image:url(:/image/images/up_arrow.png)\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"border-image:url(:/image/images/down_arrow.png)\n"
"}\n"
"*/\n"
"\n"
"QDoubleSpinBox::up-button:pressed {\n"
"margin-top:3px;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:pressed {\n"
"margin-bottom:3px;\n"
"}\n"
"/*QSpinBox*/\n"
"QDoubleSpinBox {\n"
"padding-right: 15px; /* make room for the arrows */\n"
"border:1px solid black;\n"
"border-radius:5px;\n"
"background:rgba(0,0,0,50);\n"
"}\n"
"/*\n"
"QDoubleSpinBox::up-button {\n"
"border-image:url(:/image/images/up_arrow.png)\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"border-image:url(:/image/images/down_arrow.png)\n"
"}\n"
"*/\n"
"\n"
"QSpinBox::up-button:pressed {\n"
"margin-top:3px;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:pressed {\n"
"margin-bottom:3px;\n"
"}\n"
"")
        self.doubleSpinBox_3.setDecimals(1)
        self.doubleSpinBox_3.setMinimum(1.0)
        self.doubleSpinBox_3.setMaximum(100.0)
        self.doubleSpinBox_3.setSingleStep(0.1)
        self.doubleSpinBox_3.setProperty("value", 30.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.verticalSlider = QtWidgets.QSlider(MainWindow)
        self.verticalSlider.setGeometry(QtCore.QRect(1340, 100, 22, 641))
        self.verticalSlider.setStyleSheet("QSlider \n"
"{\n"
"    background-color: rgba(22, 22, 22, 0.7);\n"
"    border-radius: 5px; /*外边框矩形倒角*/\n"
"}\n"
" \n"
"QSlider::add-page:vertical \n"
"{\n"
"    background-color: #7A7B79;\n"
"    width:5px;\n"
"    border-radius: 2px;\n"
"}\n"
" \n"
"QSlider::sub-page:vertical \n"
"{\n"
"    background-color: #7A7B79;\n"
"    width:5px;\n"
"    border-radius: 2px;\n"
"}\n"
" \n"
"QSlider::groove:vertical \n"
"{\n"
"    background:transparent;\n"
"    width:6px;\n"
"}\n"
" \n"
"QSlider::handle:vertical    \n"
"{\n"
"    height: 14px;  \n"
"    width: 14px;\n"
"    margin: 0px -4px 0px -4px;\n"
"    border-radius: 7px;\n"
"    background: white;\n"
"}")
        self.verticalSlider.setMinimum(1)
        self.verticalSlider.setMaximum(1000)
        self.verticalSlider.setProperty("value", 700)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.pushButton_in = QtWidgets.QPushButton(MainWindow)
        self.pushButton_in.setGeometry(QtCore.QRect(1410, 740, 131, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton_in.setFont(font)
        self.pushButton_in.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_in.setObjectName("pushButton_in")
        self.pushButton_result = QtWidgets.QPushButton(MainWindow)
        self.pushButton_result.setGeometry(QtCore.QRect(1710, 740, 131, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton_result.setFont(font)
        self.pushButton_result.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_result.setObjectName("pushButton_result")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(MainWindow)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(578, 790, 661, 101))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_main = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_main.setMaximumSize(QtCore.QSize(300, 25))
        self.label_main.setObjectName("label_main")
        self.gridLayout_3.addWidget(self.label_main, 0, 0, 1, 1)
        self.label_main_1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_main_1.setMaximumSize(QtCore.QSize(300, 50))
        self.label_main_1.setObjectName("label_main_1")
        self.gridLayout_3.addWidget(self.label_main_1, 1, 0, 1, 1)
        self.label_vice_1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_vice_1.setMaximumSize(QtCore.QSize(300, 50))
        self.label_vice_1.setObjectName("label_vice_1")
        self.gridLayout_3.addWidget(self.label_vice_1, 1, 1, 1, 1)
        self.label_vice = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_vice.setMaximumSize(QtCore.QSize(300, 25))
        self.label_vice.setObjectName("label_vice")
        self.gridLayout_3.addWidget(self.label_vice, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(MainWindow)
        self.label_11.setGeometry(QtCore.QRect(640, 20, 441, 61))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(MainWindow)
        self.label_12.setGeometry(QtCore.QRect(780, 700, 181, 31))
        self.label_12.setObjectName("label_12")
        self.pushButton_start = QtWidgets.QPushButton(MainWindow)
        self.pushButton_start.setGeometry(QtCore.QRect(10, 1000, 200, 75))
        self.pushButton_start.setMinimumSize(QtCore.QSize(200, 75))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_stop = QtWidgets.QPushButton(MainWindow)
        self.pushButton_stop.setGeometry(QtCore.QRect(290, 1000, 200, 75))
        self.pushButton_stop.setMinimumSize(QtCore.QSize(200, 75))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.pushButton_out = QtWidgets.QPushButton(MainWindow)
        self.pushButton_out.setGeometry(QtCore.QRect(1560, 740, 131, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton_out.setFont(font)
        self.pushButton_out.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_out.setObjectName("pushButton_out")
        self.label_main_2 = QtWidgets.QLabel(MainWindow)
        self.label_main_2.setGeometry(QtCore.QRect(596, 880, 300, 50))
        self.label_main_2.setMaximumSize(QtCore.QSize(300, 50))
        self.label_main_2.setScaledContents(True)
        self.label_main_2.setObjectName("label_main_2")
        self.label_vice_2 = QtWidgets.QLabel(MainWindow)
        self.label_vice_2.setGeometry(QtCore.QRect(921, 880, 300, 50))
        self.label_vice_2.setMaximumSize(QtCore.QSize(300, 50))
        self.label_vice_2.setObjectName("label_vice_2")
        self.label_RingNum = QtWidgets.QLabel(MainWindow)
        self.label_RingNum.setGeometry(QtCore.QRect(970, 700, 31, 31))
        self.label_RingNum.setObjectName("label_RingNum")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(MainWindow)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(1370, 810, 491, 261))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_13.setMaximumSize(QtCore.QSize(1250, 40))
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.label_result = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_result.setObjectName("label_result")
        self.verticalLayout_5.addWidget(self.label_result)
        self.frame = QtWidgets.QFrame(MainWindow)
        self.frame.setGeometry(QtCore.QRect(540, 970, 120, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(MainWindow)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(510, 940, 823, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_recover = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_recover.setMinimumSize(QtCore.QSize(200, 75))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.pushButton_recover.setFont(font)
        self.pushButton_recover.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_recover.setObjectName("pushButton_recover")
        self.horizontalLayout.addWidget(self.pushButton_recover)
        self.pushButton_help = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_help.setMinimumSize(QtCore.QSize(200, 75))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.pushButton_help.setFont(font)
        self.pushButton_help.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_help.setObjectName("pushButton_help")
        self.horizontalLayout.addWidget(self.pushButton_help)
        self.pushButton_return = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_return.setMinimumSize(QtCore.QSize(200, 75))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.pushButton_return.setFont(font)
        self.pushButton_return.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_return.setObjectName("pushButton_return")
        self.horizontalLayout.addWidget(self.pushButton_return)
        self.pushButton_exit = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_exit.setMinimumSize(QtCore.QSize(200, 75))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.horizontalLayout.addWidget(self.pushButton_exit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mplwidget = MPL_WIDGET(self.centralwidget)
        self.mplwidget.raise_()
        self.mplwidget.setObjectName("mplwidget")
        self.Interference_Image.addWidget(self.mplwidget)





        self.label_main_2.setPixmap(QtGui.QPixmap("img/标线.jpg").scaled(300, 300))
        self.label_vice_2.setPixmap(QtGui.QPixmap("img/标线.jpg").scaled(300, 300))
        self.label_vice_1.setStyleSheet("QLabel {border-image: url(img/100.jpg) 0 12745 145 200;}")  ## 446 13391*213 12745,200= 0
        self.label_main_1.setStyleSheet("QLabel {border-image: url(img/100.jpg) 0 945 145 12000;}")  ## 446 13391*213 945,12000= 100

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        for i in range(40, 20, -1):
                StrTemp = str(i) + "环"
                item = self.tableWidget.verticalHeaderItem(40 - i)
                item.setText(_translate("MainWindow", StrTemp))

        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "左位置mm"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "右位置mm"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "直径mm"))
        self.comboBox_h.setItemText(0, _translate("MainWindow", "曲率半径"))
        self.comboBox_h.setItemText(1, _translate("MainWindow", "介质折射率"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">测量内容</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">实验参数</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">入射波长λ(nm)</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">曲率半径R(m)</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">传播介质</span></p></body></html>"))
        self.comboBox_n.setItemText(0, _translate("MainWindow", "空气"))
        self.comboBox_n.setItemText(1, _translate("MainWindow", "酒精"))
        self.comboBox_n.setItemText(2, _translate("MainWindow", "盐水"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">实验目的</span></p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">1.观察光的等厚干涉现象。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">2.学习利用干涉现象测量平凸透镜曲率半径的方法。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">3.学习使用读数显微镜。</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">原理图</span></p></body></html>"))
        self.pushButton_in.setText(_translate("MainWindow", "写入数据"))
        self.pushButton_result.setText(_translate("MainWindow", "开始计算"))
        self.label_main.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#000000;\">主尺</span></p></body></html>"))
        # self.label_main_1.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"img/40.jpg\"/></p></body></html>"))
        # self.label_vice_1.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"img/100.jpg\"/></p></body></html>"))
        self.label_vice.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#000000;\">副尺</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600;\">牛顿环干涉实验</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">当前已过环数：</span></p></body></html>"))
        self.pushButton_start.setText(_translate("MainWindow", "原理演示"))
        self.pushButton_stop.setText(_translate("MainWindow", "暂停演示"))
        self.pushButton_out.setText(_translate("MainWindow", "清除数据"))
        # self.label_main_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"img/标线.jpg\"/></p></body></html>"))
        # self.label_vice_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"img/标线.jpg\"/></p></body></html>"))
        self.label_RingNum.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">0</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">结果展示</span></p><p><br/></p></body></html>"))
        self.label_result.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">计算结果</span></p></body></html>"))
        self.pushButton_recover.setText(_translate("MainWindow", "恢复默认"))
        self.pushButton_help.setText(_translate("MainWindow", "帮助文档"))
        self.pushButton_return.setText(_translate("MainWindow", "返回主界面"))
        self.pushButton_exit.setText(_translate("MainWindow", "退出"))

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showFullScreen()
    sys.exit(app.exec())
