# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1319, 842)
        MainWindow.setStyleSheet("#MainWindow{background-image: url(img/background.jpg);}")
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(390, 100, 431, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_exit = QtWidgets.QPushButton(MainWindow)
        self.pushButton_exit.setGeometry(QtCore.QRect(1820, 0, 100, 60))
        self.pushButton_exit.setMinimumSize(QtCore.QSize(100, 60))
        self.pushButton_exit.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.tabWidget = QtWidgets.QTabWidget(MainWindow)
        self.tabWidget.setGeometry(QtCore.QRect(130, 190, 1091, 481))
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setStyleSheet("\n"
"QTabBar::tab{\n"
"    background-color: rgb(108, 117, 125, 95);\n"
"    font-family:宋体;    /*设置tab中的文本的字体*/\n"
"    font-size:28pt;\n"
"    color:#ffffff;    /*设置tab中的文本的颜色*/\n"
"    border-radius: 15px;    /*设置tab的边框的圆角*/\n"
"    min-width: 8px;\n"
"    max-width: 80px;\n"
"    min-height: 225px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:selected{\n"
"    background-color: rgb(11, 14, 17, 200);/*#0B0E11;*/\n"
"}\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 311, 464))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.pushButton_MichelsonInterferometer = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_MichelsonInterferometer.setMinimumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_MichelsonInterferometer.setFont(font)
        self.pushButton_MichelsonInterferometer.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_MichelsonInterferometer.setObjectName("pushButton_MichelsonInterferometer")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_MichelsonInterferometer)
        self.pushButton_NewtonRing = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_NewtonRing.setMinimumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_NewtonRing.setFont(font)
        self.pushButton_NewtonRing.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_NewtonRing.setObjectName("pushButton_NewtonRing")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_NewtonRing)
        self.pushButton_SplittingInterference = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_SplittingInterference.setMinimumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_SplittingInterference.setFont(font)
        self.pushButton_SplittingInterference.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_SplittingInterference.setObjectName("pushButton_SplittingInterference")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButton_SplittingInterference)
        self.pushButton_DoubleSlitDiffraction = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_DoubleSlitDiffraction.setMinimumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_DoubleSlitDiffraction.setFont(font)
        self.pushButton_DoubleSlitDiffraction.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_DoubleSlitDiffraction.setObjectName("pushButton_DoubleSlitDiffraction")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pushButton_DoubleSlitDiffraction)
        self.pushButton_RoundHoleDiffraction = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_RoundHoleDiffraction.setMinimumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_RoundHoleDiffraction.setFont(font)
        self.pushButton_RoundHoleDiffraction.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_RoundHoleDiffraction.setObjectName("pushButton_RoundHoleDiffraction")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.pushButton_RoundHoleDiffraction)
        self.pushButton_GratingDiffraction = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_GratingDiffraction.setMinimumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_GratingDiffraction.setFont(font)
        self.pushButton_GratingDiffraction.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_GratingDiffraction.setObjectName("pushButton_GratingDiffraction")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.pushButton_GratingDiffraction)
        self.pushButton_YangDoubleSlit = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_YangDoubleSlit.setMinimumSize(QtCore.QSize(300, 60))
        self.pushButton_YangDoubleSlit.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_YangDoubleSlit.setFont(font)
        self.pushButton_YangDoubleSlit.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_YangDoubleSlit.setObjectName("pushButton_YangDoubleSlit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.pushButton_YangDoubleSlit)
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.tab)
        self.webEngineView.setGeometry(QtCore.QRect(330, 10, 701, 411))
        self.webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView.setObjectName("webEngineView")
        self.pushButton_in = QtWidgets.QPushButton(self.tab)
        self.pushButton_in.setGeometry(QtCore.QRect(820, 420, 200, 51))
        self.pushButton_in.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_in.setFont(font)
        self.pushButton_in.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_in.setObjectName("pushButton_in")
        self.pushButton_read = QtWidgets.QPushButton(self.tab)
        self.pushButton_read.setGeometry(QtCore.QRect(330, 420, 200, 51))
        self.pushButton_read.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_read.setFont(font)
        self.pushButton_read.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_read.setObjectName("pushButton_read")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_measure = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_measure.setGeometry(QtCore.QRect(0, 0, 300, 60))
        self.pushButton_measure.setMinimumSize(QtCore.QSize(300, 60))
        self.pushButton_measure.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_measure.setFont(font)
        self.pushButton_measure.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,20);\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"#button3 {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_measure.setObjectName("pushButton_measure")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">光学实验仿真平台</span></p></body></html>"))
        self.pushButton_exit.setText(_translate("MainWindow", "退出"))
        self.pushButton_MichelsonInterferometer.setText(_translate("MainWindow", "迈克尔逊干涉实验"))
        self.pushButton_NewtonRing.setText(_translate("MainWindow", "牛顿环干涉实验"))
        self.pushButton_SplittingInterference.setText(_translate("MainWindow", "劈尖干涉实验"))
        self.pushButton_DoubleSlitDiffraction.setText(_translate("MainWindow", "双缝衍射实验"))
        self.pushButton_RoundHoleDiffraction.setText(_translate("MainWindow", "圆孔衍射实验"))
        self.pushButton_GratingDiffraction.setText(_translate("MainWindow", "光栅衍射实验"))
        self.pushButton_YangDoubleSlit.setText(_translate("MainWindow", "杨氏双缝干涉实验"))
        self.pushButton_in.setText(_translate("MainWindow", "进入实验"))
        self.pushButton_read.setText(_translate("MainWindow", "阅读原理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "仿真实验"))
        self.pushButton_measure.setText(_translate("MainWindow", "测量及误差处理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "数据处理"))
from PyQt5 import QtWebEngineWidgets



